baseurl = "https://lvzh2012.github.io/"
languageCode = "zh-CN"
title = "LVZHENHUA'S BLOG"
theme = "lvzh"

ignoreLogs = ["warning-goldmark-raw-html"]

copyright = "Copyright © 2024-2026 Lv·Z·H"
rssLimit = 20

defaultContentLanguage = "zh"
hasCJKLanguage = true

[pagination]
  pagerSize = 12

[permalinks]
  posts = "/posts/:slug.html"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[params]
  description = "iOS / Android 开发笔记"
  author = "Lv·Z·H"

  [params.hero]
    subtitle = "AI 时代的移动开发实践"
